import React from "react";
import { hot } from "react-hot-loader";

const HelloWorld = () => {
  return (
    <div>
      <h1>Hello World!</h1>
      <p>This HTML file was generated on the server</p>
      <p>The bundle.js was generated by webpack and contains out app</p>
    </div>
  );
};

// Will use hot-loader during development
export default hot(module)(HelloWorld);
